### ISSUE TITLE
Make it on private Cloud server insted seashells.io

### ISSUE THREAD

**Issue by yahyaahrika** [anishathalye/seashells#20] opened 2020-11-02 07:53 UTC
I try to make own server show the Output in Realtime like 
CLI : *"Asterisk -rvvv"*
Every time send new information 
Could you share with asf Code are in Server (seashells.io) ?

**Comment by anishathalye** [comment] 2020-11-06 20:57
I think this is a dupe of #2. It is now on my to-do list to open-source the server, but it's not a high-priority thing, so it hasn't happened yet.

**Closed as completed by anishathalye** 2020-11-06 20:57 UTC
