### ISSUE TITLE
ability to run your own seashells server

### ISSUE THREAD

**Issue by ssbarnea** [anishathalye/seashells#15] opened 2018-07-31 09:51 UTC
it would be extremely useful to be able to run run my own seashell server as this would allow custom expire times and ability to unpublished documents in case some private information got logged by mistake.

Probably the best way to do this would be by publishing a container as this would make installation and upgrade much easier, also avoiding an endless number of packaging solutions for each platform.

**Comment by anishathalye** [comment] 2018-07-31 11:39
Seashells server code is not open-source; see #2

**Comment by anishathalye** [comment] 2019-02-05 03:14
Closing as a duplicate of #2. The plan is to open-source the server code "soon" (hopefully within a week or two).

**Closed as completed by anishathalye** 2019-02-05 03:14 UTC

**Comment by anishathalye** [comment] 2023-05-09 11:23
The seashells server was open-sourced some time ago: https://github.com/anishathalye/seashells-server
